create sequence hibernate_sequence start 1 increment 1;

CREATE TABLE user_info (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(255) NULL,
	first_name varchar(25) NULL,
	last_name varchar(25) NULL,
	"password" varchar(255) NULL,
	CONSTRAINT user_info_pkey PRIMARY KEY (id)
);

CREATE TABLE category (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"label" varchar(255) NULL,
	CONSTRAINT category_pkey PRIMARY KEY (id)
);

CREATE TABLE book (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	deleted bool NOT NULL,
	status int4 NULL,
	title varchar(255) NULL,
	category_id int4 NULL,
	user_id int4 NULL,
	CONSTRAINT book_pkey PRIMARY KEY (id),
	CONSTRAINT fk_book_category FOREIGN KEY (category_id) REFERENCES category(id),
	CONSTRAINT fk_book_userinfo FOREIGN KEY (user_id) REFERENCES user_info(id)
);

CREATE TABLE borrow (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	ask_date date NULL,
	close_date date NULL,
	book_id int4 NULL,
	borrower_id int4 NULL,
	lender_id int4 NULL,
	CONSTRAINT borrow_pkey PRIMARY KEY (id),
	CONSTRAINT fk_borrow_lender FOREIGN KEY (lender_id) REFERENCES user_info(id),
	CONSTRAINT fk_borrow_borrower FOREIGN KEY (borrower_id) REFERENCES user_info(id),
	CONSTRAINT fk_borrom_book FOREIGN KEY (book_id) REFERENCES book(id)
);